# Handling Errors

이전 챕터에서는 서버 작업을 사용하여 데이터를 변경하는 방법을 배웠습니다. JavaScript의 `try/catch` 문과 Next.js API를 사용하여 오류를 *정상적으로* 처리하는 방법을 살펴보겠습니다.

이 챕터에서 다룰 주제는 다음과 같습니다.

- 특별한 `error.tsx` 파일을 사용하여 경로 세그먼트에서 오류를 포착하고 사용자에게 대체 UI를 표시하는 방법입니다.
- `notFound` 함수 및 `not-found` 파일을 사용하여 404 오류(존재하지 않는 리소스의 경우)를 처리하는 방법

## **[서버 작업에 `try/catch` 추가](https://nextjs.org/learn/dashboard-app/error-handling#adding-trycatch-to-server-actions)**

먼저 오류를 적절하게 처리할 수 있도록 자바스크립트의 `try/catch` 문을 서버 작업에 추가해 보겠습니다.

이 작업을 수행하는 방법을 알고 있다면 서버 작업을 업데이트하는 데 몇 분 정도 시간을 투자하거나 아래 코드를 복사하세요:

/app/lib/actions.ts

```tsx
export async function createInvoice(formData: FormData) {
  const { customerId, amount, status } = CreateInvoice.parse({
    customerId: formData.get('customerId'),
    amount: formData.get('amount'),
    status: formData.get('status'),
  });
 
  const amountInCents = amount * 100;
  const date = new Date().toISOString().split('T')[0];
 
  try {
    await sql`
      INSERT INTO invoices (customer_id, amount, status, date)
      VALUES (${customerId}, ${amountInCents}, ${status}, ${date})
    `;
  } catch (error) {
    return {
      message: 'Database Error: Failed to Create Invoice.',
    };
  }
 
  revalidatePath('/dashboard/invoices');
  redirect('/dashboard/invoices');
}
```

/app/lib/actions.ts

```tsx
export async function updateInvoice(id: string, formData: FormData) {
  const { customerId, amount, status } = UpdateInvoice.parse({
    customerId: formData.get('customerId'),
    amount: formData.get('amount'),
    status: formData.get('status'),
  });
 
  const amountInCents = amount * 100;
 
  try {
    await sql`
        UPDATE invoices
        SET customer_id = ${customerId}, amount = ${amountInCents}, status = ${status}
        WHERE id = ${id}
      `;
  } catch (error) {
    return { message: 'Database Error: Failed to Update Invoice.' };
  }
 
  revalidatePath('/dashboard/invoices');
  redirect('/dashboard/invoices');
}
```

/app/lib/actions.ts

```tsx
export async function deleteInvoice(id: string) {
  try {
    await sql`DELETE FROM invoices WHERE id = ${id}`;
    revalidatePath('/dashboard/invoices');
    return { message: 'Deleted Invoice.' };
  } catch (error) {
    return { message: 'Database Error: Failed to Delete Invoice.' };
  }
}
```

`try/catch` 블록 외부에서 `리디렉션`이 어떻게 호출되는지 확인하세요. 이는 `redirect`가 `catch` 블록에 의해 포착되는 오류를 발생시켜 작동하기 때문입니다. 이를 방지하려면 `try/catch` 후에 **리디렉션`을 호출하면 됩니다. `redirect`는 `try`가 성공한 경우에만 연결할 수 있습니다.

이제 서버 작업에서 오류가 발생하면 어떤 일이 발생하는지 확인해 보겠습니다. 이전에 오류를 발생시켜 이를 수행할 수 있습니다. 예를 들어 `deleteInvoice` 작업에서 함수 상단에 오류가 발생합니다:

/app/lib/actions.ts

```tsx
export async function deleteInvoice(id: string) {
  throw new Error('Failed to Delete Invoice');
 
  // Unreachable code block
  try {
    await sql`DELETE FROM invoices WHERE id = ${id}`;
    revalidatePath('/dashboard/invoices');
    return { message: 'Deleted Invoice' };
  } catch (error) {
    return { message: 'Database Error: Failed to Delete Invoice' };
  }
}
```

송장을 삭제하려고 하면 localhost에 오류가 표시됩니다.

이러한 오류를 확인하면 잠재적인 문제를 조기에 발견할 수 있으므로 개발 중에 도움이 됩니다. 그러나 갑작스러운 오류를 방지하고 애플리케이션이 계속 실행될 수 있도록 사용자에게 오류를 표시할 수도 있습니다.

여기에 Next.js [error.tsx](https://nextjs.org/docs/app/api-reference/file-conventions/error) 파일이 들어옵니다.

## **[`error.tsx`를 사용하여 모든 오류 처리](https://nextjs.org/learn/dashboard-app/error-handling#handling-all-errors-with-errortsx)**

`error.tsx` 파일을 사용하여 경로 세그먼트의 UI 경계를 정의할 수 있습니다. 예상치 못한 오류에 대한 **포괄** 역할을 하며 사용자에게 대체 UI를 표시할 수 있습니다.

`/dashboard/invoices` 폴더 안에 `error.tsx`라는 새 파일을 만들고 다음 코드를 붙여넣습니다:

/dashboard/invoices/error.tsx

```tsx
'use client';
 
import { useEffect } from 'react';
 
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // Optionally log the error to an error reporting service
    console.error(error);
  }, [error]);
 
  return (
    <main className="flex h-full flex-col items-center justify-center">
      <h2 className="text-center">Something went wrong!</h2>
      <button
        className="mt-4 rounded-md bg-blue-500 px-4 py-2 text-sm text-white transition-colors hover:bg-blue-400"
        onClick={
          // Attempt to recover by trying to re-render the invoices route
          () => reset()
        }
      >
        Try again
      </button>
    </main>
  );
}
```

위의 코드에서 알 수 있는 몇 가지 사항이 있습니다.

- **"use client"** - `error.tsx`는 클라이언트 컴포넌트여야 합니다.
- 두 개의 props:
    - `error`: 이 개체는 JavaScript의 기본 [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) 개체의 인스턴스입니다.
    - `reset`: 오류 경계를 재설정하는 기능입니다. 실행되면 함수는 경로 세그먼트를 다시 렌더링하려고 시도합니다.


청구서를 다시 삭제하려고 하면 다음 UI가 표시됩니다:

![image01](https://nextjs.org/_next/image?url=%2Flearn%2Fdark%2Ferror-page.png&w=1920&q=75&dpl=dpl_7qDwkTDwmgWzVYKGukeHHPrgxfLF)

## **[`notFound` 기능으로 404 오류 처리](https://nextjs.org/learn/dashboard-app/error-handling#handling-404-errors-with-the-notfound-function)**

오류를 적절하게 처리할 수 있는 또 다른 방법은 `notFound` 기능을 사용하는 것입니다. `error.tsx`는 **모든** 오류를 잡는 데 유용하지만, 존재하지 않는 리소스를 가져오려고 할 때 `notFound`를 사용할 수 있습니다.

예를 들어 http://localhost:3000/dashboard/invoices/2e94d1ed-d220-449f-9f11-f0bbceed9645/edit를 방문하세요.

이는 데이터베이스에 존재하지 않는 가짜 UUID입니다.

`error.tsx`가 정의된 `/invoices`의 하위 경로이기 때문에 `error.tsx`가 시작되는 것을 즉시 확인할 수 있습니다.

그러나 좀 더 구체적으로 설명하고 싶다면 404 오류를 표시하여 사용자가 액세스하려는 리소스를 찾을 수 없음을 알릴 수 있습니다.

`data.ts`의 `fetchInvoiceById` 함수로 이동하고 콘솔에서 반환된 `invoice`를 기록하여 리소스를 찾을 수 없음을 확인할 수 있습니다:

/app/lib/data.ts

```tsx
export async function fetchInvoiceById(id: string) {
  noStore();
  try {
    // ...
 
    console.log(invoice); // Invoice is an empty array []
    return invoice[0];
  } catch (error) {
    console.error('Database Error:', error);
    throw new Error('Failed to fetch invoice.');
  }
}
```

이제 인보이스가 데이터베이스에 존재하지 않는다는 것을 알았으므로 `notFound`를 사용하여 처리해 보겠습니다. `/dashboard/invoices/[id]/edit/page.tsx`로 이동하여 `'next/navigation'`에서 `{ notFound }`를 가져옵니다.

그런 다음 인보이스가 존재하지 않는 경우 조건을 사용하여 `notFound`를 호출할 수 있습니다:

/dashboard/invoices/[id]/edit/page.tsx

```tsx
import { fetchInvoiceById, fetchCustomers } from '@/app/lib/data';
import { updateInvoice } from '@/app/lib/actions';
import { notFound } from 'next/navigation';
 
export default async function Page({ params }: { params: { id: string } }) {
  const id = params.id;
  const [invoice, customers] = await Promise.all([
    fetchInvoiceById(id),
    fetchCustomers(),
  ]);
 
  if (!invoice) {
    notFound();
  }
 
  // ...
}
```

좋습니다! 이제 `<page>`에서 특정 인보이스를 찾을 수 없으면 오류가 발생합니다. 사용자에게 오류 UI를 표시합니다. `/edit` 폴더 안에 `not-found.tsx` 파일을 만듭니다.

![image02](https://nextjs.org/_next/image?url=%2Flearn%2Fdark%2Fnot-found-file.png&w=3840&q=75&dpl=dpl_7qDwkTDwmgWzVYKGukeHHPrgxfLF)

Then, inside the `not-found.tsx` file, paste the following the code:

/dashboard/invoices/[id]/edit/not-found.tsx

```tsx
import Link from 'next/link';
import { FaceFrownIcon } from '@heroicons/react/24/outline';
 
export default function NotFound() {
  return (
    <main className="flex h-full flex-col items-center justify-center gap-2">
      <FaceFrownIcon className="w-10 text-gray-400" />
      <h2 className="text-xl font-semibold">404 Not Found</h2>
      <p>Could not find the requested invoice.</p>
      <Link
        href="/dashboard/invoices"
        className="mt-4 rounded-md bg-blue-500 px-4 py-2 text-sm text-white transition-colors hover:bg-blue-400"
      >
        Go Back
      </Link>
    </main>
  );
}
```

경로를 새로 고침하면 이제 다음 UI가 표시됩니다:

![image03](https://nextjs.org/_next/image?url=%2Flearn%2Fdark%2F404-not-found-page.png&w=1920&q=75&dpl=dpl_7qDwkTDwmgWzVYKGukeHHPrgxfLF)

명심해야 할 점은 `notFound`가 `error.tsx`보다 우선하므로 더 구체적인 오류를 처리하고 싶을 때 문의할 수 있다는 것입니다!

### 퀴즈를 풀 시간입니다!
지식을 테스트하고 방금 배운 내용을 확인하세요.
Next.js의 어떤 파일이 경로 세그먼트에서 예상치 못한 오류를 포착하는 역할을 합니까?

- 404.tsx
- not-found.tsx
- error.tsx
- catch-all.tsx

## **[추가 읽기](https://nextjs.org/learn/dashboard-app/error-handling#further-reading)**

Next.js의 오류 처리에 대해 자세히 알아보려면 다음 문서를 확인하세요.:

- [Error Handling](https://nextjs.org/docs/app/building-your-application/routing/error-handling)
- `[error.js` API Reference](https://nextjs.org/docs/app/api-reference/file-conventions/error)
- `[notFound()` API Reference](https://nextjs.org/docs/app/api-reference/functions/not-found)
- `[not-found.js` API Reference](https://nextjs.org/docs/app/api-reference/file-conventions/not-found)